CREATE TABLE IF NOT EXISTS band (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    CONSTRAINT pk_band PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS language_texts (
    band_id BIGINT NOT NULL,
    languages TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    band_id BIGINT NOT NULL,
    genres TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS countrys (
    band_id BIGINT NOT NULL,
    countrys TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS song (
    song_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    band_id BIGINT,
    name_song TEXT NOT NULL,
    text_song TEXT,
    release_date DATE,
    language TEXT,
    CONSTRAINT pk_song PRIMARY KEY (song_id)
);

CREATE INDEX IF NOT EXISTS idx_band_name ON band (name);
-- denormalised copy of language_texts.languages: lets us pick a random song of one language fast
ALTER TABLE song ADD COLUMN IF NOT EXISTS language TEXT;
CREATE INDEX IF NOT EXISTS idx_song_band_id ON song (band_id);
CREATE INDEX IF NOT EXISTS idx_song_language_id ON song (language, song_id);
CREATE INDEX IF NOT EXISTS idx_language_texts_band_id ON language_texts (band_id, languages);
CREATE INDEX IF NOT EXISTS idx_genres_band_id ON genres (band_id);
CREATE INDEX IF NOT EXISTS idx_countrys_band_id ON countrys (band_id);
